### PR TITLE
Revert "It fails if ~/securedata/settings.json does not exist."

### PR DESCRIPTION
**Pull request by tylerjwoodfin**
Causes several problems- 
1. `securedata config` repeatedly recreates settings.json, causing data loss
2. Pressing enter after `securedata config` and no input throws an error
3. getItem and setItem no longer work

### CODE REVIEW

**Comment by tylerjwoodfin** [comment]
4. `path_log` has `//`

**Comment by tylerjwoodfin** [comment]
@arvinddeshpande `path_log` should also be in the main `settings.json`; I use `config.json` within the package contents just to point to the data folder (which contains `settings.json` and logs).

I think you had a few good ideas, though. Next time, I'll pull your branch and test before merging.

**Comment by arvinddeshpande** [comment]
Although I saw you were using config.json within the package, what happens when multiple users invoke the "securedata config" ? Especially when the package in installed with "sudo pip install securedata"?

**Comment by arvinddeshpande** [comment]
`pi@raspberrypi:~/Git/securedata $ sudo pip install securedata
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting securedata
  Downloading https://www.piwheels.org/simple/securedata/securedata-2022.1.9.1-py3-none-any.whl (6.5 kB)
Installing collected packages: securedata
Successfully installed securedata-2022.1.9.1
pi@raspberrypi:~/Git/securedata $ which securedata
/usr/local/bin/securedata
pi@raspberrypi:~/Git/securedata $ securedata config
-bash: /home/pi/.local/bin/securedata: No such file or directory
pi@raspberrypi:~/Git/securedata $ /usr/local/bin/securedata config
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/securedata/securedata.py", line 173, in getConfigItem
    with open(configPath, 'r+') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.9/dist-packages/securedata/config.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/securedata", line 5, in <module>
    from securedata.securedata import main
  File "/usr/local/lib/python3.9/dist-packages/securedata/securedata.py", line 285, in <module>
    main()
  File "/usr/local/lib/python3.9/dist-packages/securedata/securedata.py", line 25, in main
    securePath = os.path.expanduser(getConfigItem('path_securedata')) or f'{os.path.expanduser("~")}/securedata'
  File "/usr/local/lib/python3.9/dist-packages/securedata/securedata.py", line 177, in getConfigItem
    setConfigItem(key, str(pathlib.Path(getItem('path_log')).resolve().parent))
  File "/usr/lib/python3.9/pathlib.py", line 1071, in __new__
    self = cls._from_parts(args, init=False)
  File "/usr/lib/python3.9/pathlib.py", line 696, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/usr/lib/python3.9/pathlib.py", line 680, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
pi@raspberrypi:~/Git/securedata $`

**Comment by arvinddeshpande** [comment]
BTW that repeated creation of the file is happening because I did not know that main() is called directly from securedata.py
from here
```
# Initialize
main()
```
when you import anything from this module, you think that you're just importing the function from the module but in fact because of the above statement, it does things inadvertently.

**Comment by tylerjwoodfin** [comment]
I'm troubleshooting `sudo securedata config` vs. `securedata config`. I see one issue that I have leftover code from a few weeks ago when I was thinking `path_log` would also go in `config.json` (at first, everything was going into config.json within the package). I'll fix this as well.

**Comment by tylerjwoodfin** [comment]
Fixed! I also fixed a couple of other quirks I found with multiple users or improperly-formatted json files. https://github.com/tylerjwoodfin/securedata/commit/66a91a81678a4f9759338cda8c8c105a975ab693

**Pull request merged**
